// Extracts only the game-icons.net glyphs Kardux actually uses (CC BY 3.0, see README.md)
// into a small, typed TypeScript module - the full set is 4000+ icons / several MB, far too
// much to ship to the browser. Run with `pnpm --filter @kardux/content icons` after editing
// the list below; the output file is committed so builds never depend on this script.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const set = JSON.parse(
    readFileSync(require.resolve('@iconify-json/game-icons/icons.json'), 'utf8'),
);

const ICONS = [
    // Atributos Pokémon
    'heart-plus',
    'muscle-up',
    'checked-shield',
    'lightning-helix',
    'magic-swirl',
    'brain',
    // Avatares
    'visored-helm',
    'spartan-helmet',
    'samurai-helmet',
    'viking-helmet',
    'centurion-helmet',
    'black-knight-helm',
    'ninja-head',
    'hooded-figure',
    'pirate-captain',
    'wizard-face',
    'witch-face',
    'woman-elf-face',
    'dwarf-face',
    'barbarian',
    'monk-face',
    'viking-head',
    'astronaut-helmet',
    'robot-golem',
    'jester-hat',
    'dragon-head',
    'wolf-head',
    'eagle-head',
    'fox-head',
    'owl',
    // Interfaz
    'crossed-swords',
    'sword-clash',
    'card-draw',
    'card-pickup',
    'card-play',
    'crown',
    'trophy-cup',
    'laurels-trophy',
    'podium-winner',
    'exit-door',
    'share',
    'chat-bubble',
    'stopwatch',
    'infinity',
    'linked-rings',
    'envelope',
    'paper-plane',
    'return-arrow',
    'cancel',
    'magic-portal',
    'dice-six-faces-five',
    'scroll-unfurled',
    'info',
    'flame',
];

const missing = ICONS.filter((name) => !set.icons[name]);
if (missing.length > 0) {
    console.error(`Missing game-icons: ${missing.join(', ')}`);
    process.exit(1);
}

const entries = ICONS.map((name) => {
    // Every game-icons body is a single <path> with fill="currentColor" on a 512x512 canvas;
    // keep only the `d` attribute so callers can style the fill freely.
    const match = /\sd="([^"]+)"/.exec(set.icons[name].body);
    if (!match) throw new Error(`Unexpected body for ${name}`);
    return `    '${name}': '${match[1]}',`;
});

const output = `// GENERATED by scripts/generate-icons.mjs - do not edit by hand.
// Icons by Lorc, Delapouite and contributors - https://game-icons.net - CC BY 3.0.

export const ICON_PATHS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;

/** All icons share this square canvas. */
export const ICON_VIEWBOX = 512;
`;

writeFileSync(join(here, '..', 'src', 'icons.generated.ts'), output);
console.warn(`Wrote ${ICONS.length} icons.`);
