import type { DeckDefinition } from './types.js';

/** Creatures from public-domain mythology - original names, original stats. */
export const MYTHIC_DECK: DeckDefinition = {
    id: 'mythic',
    label: 'Criaturas Míticas',
    tagline: 'Leyendas de todos los tiempos',
    description:
        'Dragones, krakens, grifos y titanes de la mitología universal. Seis atributos para duelos épicos.',
    coverIcon: 'dragon-head',
    accent: '#ff7d47',
    attributes: [
        { key: 'poder', label: 'Poder', icon: 'muscle-up', higherIsBetter: true },
        { key: 'defensa', label: 'Defensa', icon: 'checked-shield', higherIsBetter: true },
        { key: 'velocidad', label: 'Velocidad', icon: 'lightning-helix', higherIsBetter: true },
        { key: 'magia', label: 'Magia', icon: 'magic-swirl', higherIsBetter: true },
        { key: 'astucia', label: 'Astucia', icon: 'brain', higherIsBetter: true },
        { key: 'resistencia', label: 'Resistencia', icon: 'heart-plus', higherIsBetter: true },
    ],
    families: [
        {
            key: 'dragones',
            label: 'Dragones',
            icon: 'dragon-head',
            palette: { from: '#ff7a3d', to: '#5c0f0f' },
            profile: { poder: 90, defensa: 78, velocidad: 62, magia: 74, astucia: 66, resistencia: 84 },
            members: [
                { name: 'Dragón Carmesí' },
                { name: 'Wyvern de Ceniza' },
                { name: 'Dragón Abisal' },
                { name: 'Sierpe Dorada' },
                { name: 'Drake de Tormenta' },
                { name: 'Dragón Rúnico' },
            ],
        },
        {
            key: 'grifos',
            label: 'Grifos',
            icon: 'griffin-symbol',
            palette: { from: '#e8b94f', to: '#5a3a0e' },
            profile: { poder: 70, defensa: 58, velocidad: 88, magia: 40, astucia: 72, resistencia: 60 },
            members: [
                { name: 'Grifo Real' },
                { name: 'Grifo de las Cumbres' },
                { name: 'Grifo Solar' },
                { name: 'Grifo Centinela' },
                { name: 'Grifo del Alba' },
                { name: 'Grifo Errante' },
            ],
        },
        {
            key: 'krakens',
            label: 'Krakens',
            icon: 'kraken-tentacle',
            palette: { from: '#35d9c4', to: '#07303a' },
            profile: { poder: 86, defensa: 70, velocidad: 40, magia: 52, astucia: 60, resistencia: 90 },
            members: [
                { name: 'Kraken Abisal' },
                { name: 'Kraken de Coral' },
                { name: 'Kraken Tempestad' },
                { name: 'Kraken Glacial' },
                { name: 'Kraken Ancestral' },
                { name: 'Kraken Sombrío' },
            ],
        },
        {
            key: 'hidras',
            label: 'Hidras',
            icon: 'hydra',
            palette: { from: '#7ad64b', to: '#1a3d10' },
            profile: { poder: 78, defensa: 64, velocidad: 50, magia: 60, astucia: 54, resistencia: 96 },
            members: [
                { name: 'Hidra de Lerna' },
                { name: 'Hidra Venenosa' },
                { name: 'Hidra del Pantano' },
                { name: 'Hidra Tricéfala' },
                { name: 'Hidra de Jade' },
                { name: 'Hidra Eterna' },
            ],
        },
        {
            key: 'golems',
            label: 'Gólems',
            icon: 'golem-head',
            palette: { from: '#b3a58a', to: '#3a3226' },
            profile: { poder: 84, defensa: 96, velocidad: 18, magia: 44, astucia: 22, resistencia: 92 },
            members: [
                { name: 'Gólem de Granito' },
                { name: 'Gólem de Obsidiana' },
                { name: 'Gólem de Bronce' },
                { name: 'Gólem Rúnico' },
                { name: 'Gólem de Arcilla' },
                { name: 'Gólem de Hierro' },
            ],
        },
        {
            key: 'espectros',
            label: 'Espectros',
            icon: 'spectre',
            palette: { from: '#9aa4c0', to: '#1c2033' },
            profile: { poder: 58, defensa: 40, velocidad: 76, magia: 92, astucia: 82, resistencia: 46 },
            members: [
                { name: 'Espectro Errante' },
                { name: 'Alma en Pena' },
                { name: 'Espectro del Faro' },
                { name: 'Banshee Lunar' },
                { name: 'Espectro Helado' },
                { name: 'Sombra Antigua' },
            ],
        },
        {
            key: 'minotauros',
            label: 'Minotauros',
            icon: 'minotaur',
            palette: { from: '#c9713b', to: '#3d1a0b' },
            profile: { poder: 92, defensa: 72, velocidad: 52, magia: 20, astucia: 44, resistencia: 86 },
            members: [
                { name: 'Minotauro del Laberinto' },
                { name: 'Minotauro de Bronce' },
                { name: 'Toro de Creta' },
                { name: 'Minotauro Furioso' },
                { name: 'Minotauro Guardián' },
                { name: 'Minotauro Rojo' },
            ],
        },
        {
            key: 'pegasos',
            label: 'Pegasos',
            icon: 'pegasus',
            palette: { from: '#8fd8ff', to: '#1b3f73' },
            profile: { poder: 52, defensa: 48, velocidad: 96, magia: 70, astucia: 64, resistencia: 58 },
            members: [
                { name: 'Pegaso Celeste' },
                { name: 'Pegaso de Plata' },
                { name: 'Pegaso Nocturno' },
                { name: 'Corcel del Viento' },
                { name: 'Pegaso Estelar' },
                { name: 'Pegaso Blanco' },
            ],
        },
        {
            key: 'centauros',
            label: 'Centauros',
            icon: 'centaur',
            palette: { from: '#a8c46a', to: '#2c3b12' },
            profile: { poder: 68, defensa: 60, velocidad: 80, magia: 46, astucia: 78, resistencia: 70 },
            members: [
                { name: 'Centauro Arquero' },
                { name: 'Centauro Sabio' },
                { name: 'Centauro del Bosque' },
                { name: 'Centauro Guerrero' },
                { name: 'Centauro Vidente' },
                { name: 'Centauro Nómada' },
            ],
        },
        {
            key: 'unicornios',
            label: 'Unicornios',
            icon: 'unicorn',
            palette: { from: '#f3a6ff', to: '#4a1a63' },
            profile: { poder: 54, defensa: 56, velocidad: 78, magia: 94, astucia: 60, resistencia: 64 },
            members: [
                { name: 'Unicornio Radiante' },
                { name: 'Unicornio de Cristal' },
                { name: 'Unicornio Lunar' },
                { name: 'Unicornio Salvaje' },
                { name: 'Unicornio Arcano' },
                { name: 'Unicornio Real' },
            ],
        },
        {
            key: 'ciclopes',
            label: 'Cíclopes',
            icon: 'cyclops',
            palette: { from: '#d4a373', to: '#4a2e14' },
            profile: { poder: 94, defensa: 80, velocidad: 28, magia: 30, astucia: 36, resistencia: 88 },
            members: [
                { name: 'Cíclope Herrero' },
                { name: 'Cíclope Pastor' },
                { name: 'Cíclope Tronante' },
                { name: 'Cíclope de la Isla' },
                { name: 'Cíclope Colosal' },
                { name: 'Cíclope Anciano' },
            ],
        },
        {
            key: 'esfinges',
            label: 'Esfinges',
            icon: 'greek-sphinx',
            palette: { from: '#f2cf7a', to: '#6b4a1a' },
            profile: { poder: 64, defensa: 70, velocidad: 46, magia: 80, astucia: 98, resistencia: 72 },
            members: [
                { name: 'Esfinge de Tebas' },
                { name: 'Esfinge del Desierto' },
                { name: 'Esfinge Guardiana' },
                { name: 'Esfinge de Arena' },
                { name: 'Esfinge Enigmática' },
                { name: 'Esfinge Dorada' },
            ],
        },
        {
            key: 'arpias',
            label: 'Arpías',
            icon: 'harpy',
            palette: { from: '#b579ea', to: '#2a0f45' },
            profile: { poder: 60, defensa: 42, velocidad: 90, magia: 56, astucia: 70, resistencia: 50 },
            members: [
                { name: 'Arpía Tormentosa' },
                { name: 'Arpía de Garras' },
                { name: 'Arpía Chillona' },
                { name: 'Arpía Veloz' },
                { name: 'Arpía Sombría' },
                { name: 'Arpía Reina' },
            ],
        },
        {
            key: 'licantropos',
            label: 'Licántropos',
            icon: 'werewolf',
            palette: { from: '#8a8fa3', to: '#20222e' },
            profile: { poder: 82, defensa: 58, velocidad: 84, magia: 38, astucia: 62, resistencia: 76 },
            members: [
                { name: 'Licántropo Alfa' },
                { name: 'Lobo de Luna Llena' },
                { name: 'Licántropo Plateado' },
                { name: 'Cazador Nocturno' },
                { name: 'Licántropo Salvaje' },
                { name: 'Licántropo Ancestral' },
            ],
        },
        {
            key: 'sirenas',
            label: 'Sirenas',
            icon: 'mermaid',
            palette: { from: '#5ec8f2', to: '#0b2f4f' },
            profile: { poder: 48, defensa: 46, velocidad: 74, magia: 88, astucia: 86, resistencia: 56 },
            members: [
                { name: 'Sirena del Arrecife' },
                { name: 'Sirena Cantora' },
                { name: 'Sirena Abisal' },
                { name: 'Sirena de Perlas' },
                { name: 'Sirena Tormenta' },
                { name: 'Sirena Reina' },
            ],
        },
        {
            key: 'serpientes',
            label: 'Serpientes Marinas',
            icon: 'sea-serpent',
            palette: { from: '#2dd4a7', to: '#063b2e' },
            profile: { poder: 80, defensa: 66, velocidad: 68, magia: 58, astucia: 52, resistencia: 82 },
            members: [
                { name: 'Leviatán Menor' },
                { name: 'Serpiente de Jade' },
                { name: 'Serpiente Colosal' },
                { name: 'Serpiente Espiral' },
                { name: 'Serpiente Nocturna' },
                { name: 'Serpiente Primordial' },
            ],
        },
    ],
};
