import type { IconName } from '../icons.generated.js';
import type { DeckDefinition, DeckMember } from './types.js';
import { text } from './types.js';

/** Creatures from public-domain mythology: original names and stats, one glyph per creature
 *  where game-icons.net has a fitting one. Stats are derived from each family's profile. */
function creature(es: string, en: string, icon?: IconName): DeckMember {
    return icon ? { name: text(es, en), icon } : { name: text(es, en) };
}

export const MYTHIC_DECK: DeckDefinition = {
    id: 'mythic',
    label: text('Criaturas Míticas', 'Mythic Creatures'),
    tagline: text('Leyendas de todos los tiempos', 'Legends of every age'),
    description: text(
        'Dragones, krakens, grifos y titanes de la mitología universal. Seis atributos para duelos épicos.',
        'Dragons, krakens, griffins and titans from world mythology. Six attributes for epic duels.',
    ),
    coverIcon: 'dragon-head',
    accent: '#ff7d47',
    attributes: [
        { key: 'poder', label: text('Poder', 'Power'), icon: 'muscle-up', higherIsBetter: true },
        {
            key: 'defensa',
            label: text('Defensa', 'Defense'),
            icon: 'checked-shield',
            higherIsBetter: true,
        },
        {
            key: 'velocidad',
            label: text('Velocidad', 'Speed'),
            icon: 'lightning-helix',
            higherIsBetter: true,
        },
        { key: 'magia', label: text('Magia', 'Magic'), icon: 'magic-swirl', higherIsBetter: true },
        { key: 'astucia', label: text('Astucia', 'Cunning'), icon: 'brain', higherIsBetter: true },
        {
            key: 'resistencia',
            label: text('Resistencia', 'Stamina'),
            icon: 'heart-plus',
            higherIsBetter: true,
        },
    ],
    families: [
        {
            key: 'dragones',
            label: text('Dragones', 'Dragons'),
            icon: 'dragon-head',
            palette: { from: '#ff7a3d', to: '#5c0f0f' },
            profile: {
                poder: 90,
                defensa: 78,
                velocidad: 62,
                magia: 74,
                astucia: 66,
                resistencia: 84,
            },
            members: [
                creature('Dragón Carmesí', 'Crimson Dragon', 'dragon-head'),
                creature('Wyvern de Ceniza', 'Ash Wyvern', 'spiked-dragon-head'),
                creature('Dragón Abisal', 'Abyssal Dragon', 'sea-dragon'),
                creature('Sierpe Dorada', 'Golden Wyrm', 'dragon-spiral'),
                creature('Drake de Tormenta', 'Storm Drake', 'dragon-breath'),
                creature('Dragón Rúnico', 'Runic Dragon', 'double-dragon'),
            ],
        },
        {
            key: 'grifos',
            label: text('Grifos', 'Griffins'),
            icon: 'griffin-symbol',
            palette: { from: '#e8b94f', to: '#5a3a0e' },
            profile: {
                poder: 70,
                defensa: 58,
                velocidad: 88,
                magia: 40,
                astucia: 72,
                resistencia: 60,
            },
            members: [
                creature('Grifo Real', 'Royal Griffin', 'griffin-symbol'),
                creature('Grifo de las Cumbres', 'Summit Griffin'),
                creature('Grifo Solar', 'Sun Griffin'),
                creature('Grifo Centinela', 'Sentinel Griffin', 'griffin-shield'),
                creature('Grifo del Alba', 'Dawn Griffin'),
                creature('Grifo Errante', 'Wandering Griffin'),
            ],
        },
        {
            key: 'krakens',
            label: text('Krakens', 'Krakens'),
            icon: 'kraken-tentacle',
            palette: { from: '#35d9c4', to: '#07303a' },
            profile: {
                poder: 86,
                defensa: 70,
                velocidad: 40,
                magia: 52,
                astucia: 60,
                resistencia: 90,
            },
            members: [
                creature('Kraken Abisal', 'Abyssal Kraken', 'kraken-tentacle'),
                creature('Kraken de Coral', 'Coral Kraken'),
                creature('Kraken Tempestad', 'Tempest Kraken', 'spiral-tentacle'),
                creature('Kraken Glacial', 'Glacial Kraken'),
                creature('Kraken Ancestral', 'Ancient Kraken', 'spiral-tentacle'),
                creature('Kraken Sombrío', 'Shadow Kraken'),
            ],
        },
        {
            key: 'hidras',
            label: text('Hidras', 'Hydras'),
            icon: 'hydra',
            palette: { from: '#7ad64b', to: '#1a3d10' },
            profile: {
                poder: 78,
                defensa: 64,
                velocidad: 50,
                magia: 60,
                astucia: 54,
                resistencia: 96,
            },
            members: [
                creature('Hidra de Lerna', 'Lernaean Hydra', 'hydra'),
                creature('Hidra Venenosa', 'Venom Hydra', 'hydra-shot'),
                creature('Hidra del Pantano', 'Marsh Hydra'),
                creature('Hidra Tricéfala', 'Three-headed Hydra', 'hydra-shot'),
                creature('Hidra de Jade', 'Jade Hydra'),
                creature('Hidra Eterna', 'Eternal Hydra'),
            ],
        },
        {
            key: 'golems',
            label: text('Gólems', 'Golems'),
            icon: 'golem-head',
            palette: { from: '#b3a58a', to: '#3a3226' },
            profile: {
                poder: 84,
                defensa: 96,
                velocidad: 18,
                magia: 44,
                astucia: 22,
                resistencia: 92,
            },
            members: [
                creature('Gólem de Granito', 'Granite Golem', 'rock-golem'),
                creature('Gólem de Obsidiana', 'Obsidian Golem', 'golem-head'),
                creature('Gólem de Bronce', 'Bronze Golem', 'metal-golem-head'),
                creature('Gólem Rúnico', 'Runic Golem', 'robot-golem'),
                creature('Gólem de Arcilla', 'Clay Golem', 'rock-golem'),
                creature('Gólem de Hierro', 'Iron Golem', 'metal-golem-head'),
            ],
        },
        {
            key: 'espectros',
            label: text('Espectros', 'Specters'),
            icon: 'spectre',
            palette: { from: '#9aa4c0', to: '#1c2033' },
            profile: {
                poder: 58,
                defensa: 40,
                velocidad: 76,
                magia: 92,
                astucia: 82,
                resistencia: 46,
            },
            members: [
                creature('Espectro Errante', 'Wandering Specter'),
                creature('Alma en Pena', 'Lost Soul'),
                creature('Espectro del Faro', 'Lighthouse Specter'),
                creature('Banshee Lunar', 'Moon Banshee'),
                creature('Espectro Helado', 'Frost Specter'),
                creature('Sombra Antigua', 'Ancient Shade'),
            ],
        },
        {
            key: 'minotauros',
            label: text('Minotauros', 'Minotaurs'),
            icon: 'minotaur',
            palette: { from: '#c9713b', to: '#3d1a0b' },
            profile: {
                poder: 92,
                defensa: 72,
                velocidad: 52,
                magia: 20,
                astucia: 44,
                resistencia: 86,
            },
            members: [
                creature('Minotauro del Laberinto', 'Labyrinth Minotaur'),
                creature('Minotauro de Bronce', 'Bronze Minotaur'),
                creature('Toro de Creta', 'Cretan Bull'),
                creature('Minotauro Furioso', 'Raging Minotaur'),
                creature('Minotauro Guardián', 'Guardian Minotaur'),
                creature('Minotauro Rojo', 'Red Minotaur'),
            ],
        },
        {
            key: 'pegasos',
            label: text('Pegasos', 'Pegasi'),
            icon: 'pegasus',
            palette: { from: '#8fd8ff', to: '#1b3f73' },
            profile: {
                poder: 52,
                defensa: 48,
                velocidad: 96,
                magia: 70,
                astucia: 64,
                resistencia: 58,
            },
            members: [
                creature('Pegaso Celeste', 'Celestial Pegasus'),
                creature('Pegaso de Plata', 'Silver Pegasus'),
                creature('Pegaso Nocturno', 'Night Pegasus'),
                creature('Corcel del Viento', 'Wind Steed'),
                creature('Pegaso Estelar', 'Star Pegasus'),
                creature('Pegaso Blanco', 'White Pegasus'),
            ],
        },
        {
            key: 'centauros',
            label: text('Centauros', 'Centaurs'),
            icon: 'centaur',
            palette: { from: '#a8c46a', to: '#2c3b12' },
            profile: {
                poder: 68,
                defensa: 60,
                velocidad: 80,
                magia: 46,
                astucia: 78,
                resistencia: 70,
            },
            members: [
                creature('Centauro Arquero', 'Archer Centaur'),
                creature('Centauro Sabio', 'Sage Centaur'),
                creature('Centauro del Bosque', 'Forest Centaur'),
                creature('Centauro Guerrero', 'Warrior Centaur'),
                creature('Centauro Vidente', 'Seer Centaur'),
                creature('Centauro Nómada', 'Nomad Centaur'),
            ],
        },
        {
            key: 'unicornios',
            label: text('Unicornios', 'Unicorns'),
            icon: 'unicorn',
            palette: { from: '#f3a6ff', to: '#4a1a63' },
            profile: {
                poder: 54,
                defensa: 56,
                velocidad: 78,
                magia: 94,
                astucia: 60,
                resistencia: 64,
            },
            members: [
                creature('Unicornio Radiante', 'Radiant Unicorn'),
                creature('Unicornio de Cristal', 'Crystal Unicorn'),
                creature('Unicornio Lunar', 'Lunar Unicorn'),
                creature('Unicornio Salvaje', 'Wild Unicorn'),
                creature('Unicornio Arcano', 'Arcane Unicorn'),
                creature('Unicornio Real', 'Royal Unicorn'),
            ],
        },
        {
            key: 'ciclopes',
            label: text('Cíclopes', 'Cyclopes'),
            icon: 'cyclops',
            palette: { from: '#d4a373', to: '#4a2e14' },
            profile: {
                poder: 94,
                defensa: 80,
                velocidad: 28,
                magia: 30,
                astucia: 36,
                resistencia: 88,
            },
            members: [
                creature('Cíclope Herrero', 'Smith Cyclops'),
                creature('Cíclope Pastor', 'Shepherd Cyclops'),
                creature('Cíclope Tronante', 'Thundering Cyclops'),
                creature('Cíclope de la Isla', 'Island Cyclops'),
                creature('Cíclope Colosal', 'Colossal Cyclops', 'jawless-cyclop'),
                creature('Cíclope Anciano', 'Elder Cyclops', 'jawless-cyclop'),
            ],
        },
        {
            key: 'esfinges',
            label: text('Esfinges', 'Sphinxes'),
            icon: 'greek-sphinx',
            palette: { from: '#f2cf7a', to: '#6b4a1a' },
            profile: {
                poder: 64,
                defensa: 70,
                velocidad: 46,
                magia: 80,
                astucia: 98,
                resistencia: 72,
            },
            members: [
                creature('Esfinge de Tebas', 'Theban Sphinx'),
                creature('Esfinge del Desierto', 'Desert Sphinx', 'egyptian-sphinx'),
                creature('Esfinge Guardiana', 'Guardian Sphinx'),
                creature('Esfinge de Arena', 'Sand Sphinx', 'egyptian-sphinx'),
                creature('Esfinge Enigmática', 'Enigmatic Sphinx'),
                creature('Esfinge Dorada', 'Golden Sphinx', 'egyptian-sphinx'),
            ],
        },
        {
            key: 'arpias',
            label: text('Arpías', 'Harpies'),
            icon: 'harpy',
            palette: { from: '#b579ea', to: '#2a0f45' },
            profile: {
                poder: 60,
                defensa: 42,
                velocidad: 90,
                magia: 56,
                astucia: 70,
                resistencia: 50,
            },
            members: [
                creature('Arpía Tormentosa', 'Stormborn Harpy'),
                creature('Arpía de Garras', 'Taloned Harpy'),
                creature('Arpía Chillona', 'Shrieking Harpy'),
                creature('Arpía Veloz', 'Swift Harpy'),
                creature('Arpía Sombría', 'Gloom Harpy'),
                creature('Arpía Reina', 'Harpy Queen'),
            ],
        },
        {
            key: 'licantropos',
            label: text('Licántropos', 'Werewolves'),
            icon: 'werewolf',
            palette: { from: '#8a8fa3', to: '#20222e' },
            profile: {
                poder: 82,
                defensa: 58,
                velocidad: 84,
                magia: 38,
                astucia: 62,
                resistencia: 76,
            },
            members: [
                creature('Licántropo Alfa', 'Alpha Werewolf', 'direwolf'),
                creature('Lobo de Luna Llena', 'Full Moon Wolf', 'wolf-howl'),
                creature('Licántropo Plateado', 'Silver Werewolf'),
                creature('Cazador Nocturno', 'Night Stalker', 'direwolf'),
                creature('Licántropo Salvaje', 'Feral Werewolf'),
                creature('Licántropo Ancestral', 'Ancient Werewolf'),
            ],
        },
        {
            key: 'sirenas',
            label: text('Sirenas', 'Sirens'),
            icon: 'mermaid',
            palette: { from: '#5ec8f2', to: '#0b2f4f' },
            profile: {
                poder: 48,
                defensa: 46,
                velocidad: 74,
                magia: 88,
                astucia: 86,
                resistencia: 56,
            },
            members: [
                creature('Sirena del Arrecife', 'Reef Siren'),
                creature('Sirena Cantora', 'Singing Siren'),
                creature('Sirena Abisal', 'Abyssal Siren'),
                creature('Sirena de Perlas', 'Pearl Siren'),
                creature('Sirena Tormenta', 'Storm Siren'),
                creature('Sirena Reina', 'Siren Queen'),
            ],
        },
        {
            key: 'serpientes',
            label: text('Serpientes Marinas', 'Sea Serpents'),
            icon: 'sea-serpent',
            palette: { from: '#2dd4a7', to: '#063b2e' },
            profile: {
                poder: 80,
                defensa: 66,
                velocidad: 68,
                magia: 58,
                astucia: 52,
                resistencia: 82,
            },
            members: [
                creature('Leviatán Menor', 'Lesser Leviathan', 'sea-dragon'),
                creature('Serpiente de Jade', 'Jade Serpent'),
                creature('Serpiente Colosal', 'Colossal Serpent', 'sea-serpent'),
                creature('Serpiente Espiral', 'Spiral Serpent'),
                creature('Serpiente Nocturna', 'Night Serpent'),
                creature('Serpiente Primordial', 'Primordial Serpent'),
            ],
        },
    ],
};
